### ISSUE TITLE
Scrollbar is increasing and decreasing in height.

### ISSUE THREAD

**Issue by adityabavadekar** [AdityaBavadekar/PinLog#2]

**Comment by adityabavadekar** [comment]
**Ok I will try to fix that. But that is mostly due to max lines on textview.**

**Comment by lodenrogue** [comment]
Is this really a bug? Seems to me that this is how all scrollbars are supposed to work. Can you provide a screenshot of the bug?

**Comment by adityabavadekar** [comment]
This is indeed a bug. This is happening as the the behavior of log textView is that if it has expanded it will collapse on click otherwise it will expand making the scrollbar increase or decrease its height.

**Comment by adityabavadekar** [comment]
https://user-images.githubusercontent.com/64344960/177118091-da548557-fb38-49f0-8a01-000231d460fa.mp4

See this is that behavior.
Here we can see that the scrollbar changes its height.

**Comment by adityabavadekar** [comment]
> Is this really a bug? Seems to me that this is how all scrollbars are supposed to work. Can you provide a screenshot of the bug?

This is the recording.

**Comment by lodenrogue** [comment]
In the video the scroll bar gets bigger when you hide content. That's expected behavior. Bigger means there's less to scroll through.

**Comment by AdityaBavadekar** [comment]
Ok thats the expected behaviour but this is not.

Uploading vidma_recorder_05072022_072307.mp4…

**Comment by adityabavadekar** [comment]
https://user-images.githubusercontent.com/64344960/177234276-56bdda3b-4f96-429f-8b5b-47df3d6067b5.mp4

Ok thats the expected behaviour but this is not.

**Comment by adityabavadekar** [comment]
It might be fixed with this https://stackoverflow.com/a/23617530

**Comment by lodenrogue** [comment]
Oh yeah that second video does look like its a bug

**Comment by adityabavadekar** [comment]
*Hi @lodenrogue, This issue has been solved for versions from [`1.0.0`](https://github.com/AdityaBavadekar/PinLog/releases/tag/1.0.0#:~:text=Scrollbar%20for%20pinlog%2Dactivity%20has%20been%20modified.)*
